version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  npm_publish:
    executor: node/default
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: |
            cd ./package/
            pwd
            ls -la
            echo -e $NPM_USER\$NPM_USER\n$NPM_EMAIL | npm login -e $NPM_EMAIL -r $NPM_REGISTRY
workflows:
  main:
    jobs:
      # - node/test
      - npm_publish #:
        # requires:
        #   - node/test
