version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  npm_publish:
    executor: node/default
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: |
            echo $NPM_PUBLISH_TOKEN
            cd ./src/
            npm login
            npm publish

workflows:
  main:
    jobs:
      - node/test
      - npm_publish:
          requires:
            - node/test
