version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  npm_publish:
    executor: node/default
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: |
            sudo npm cache clean
            echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL"
            echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL" | npm login -e $NPM_EMAIL -r $NPM_REGISTRY
            cd ./package
            npm publish
            cd ..

workflows:
  main:
    jobs:
      # - node/test
      - npm_publish #:
        # requires:
        #   - node/test
