version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  npm_publish:
    executor: node/default
    steps:
      - checkout # checkout source code to working directorys
      - run:
          command: |
            cd ./package
            npm install -g npm-cli-login
            npm-cli-login
            npm publish
            cd ..

workflows:
  main:
    jobs:
      # - node/test
      - npm_publish #:
        # requires:
        #   - node/test
