version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  npm_publish:
    executor: node/default
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: |
            npm init -y
            npm i npm-cli-login
            npm-cli-login -u NPM_USER -p NPM_PASS -e NPM_EMAIL
            npm publish ./package

workflows:
  main:
    jobs:
      # - node/test
      - npm_publish #:
        # requires:
        #   - node/test
