version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  npm_publish:
    executor: node/default
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: |
            cd ./src/
            npm login -e $NPM_EMAIL -r $NPM_REGISTRY << EOF
              $NPM_USERNAME
              $NPM_PASSWORD
              $NPM_EMAIL
              EOF
            npm publish

workflows:
  main:
    jobs:
      # - node/test
      - npm_publish #:
        # requires:
        #   - node/test
